"""Build the two static pages. Python 3 standard library only."""
from pathlib import Path
from html import escape

ROOT = Path(__file__).resolve().parents[1]
LANG = 0

def t(zh, en):
    return zh if LANG == 0 else en

def pills(items):
    return '<div class="pills">' + ''.join(f'<span>{escape(x)}</span>' for x in items) + '</div>'

def bullets(items):
    return '<ul>' + ''.join(f'<li>{x}</li>' for x in items) + '</ul>'

def heading(number, zh, en, note=''):
    return f'<div class="section-heading"><h2><span class="section-number">{number}</span>{t(zh,en)}</h2><span class="section-note">{note}</span></div>'

def entry(title, role, date, summary, details, tags=()):
    return f'''<article class="card entry"><div class="entry-heading"><div><h4>{title}</h4><p class="role">{role}</p></div><span class="date">{date}</span></div><p>{summary}</p>{pills(tags) if tags else ''}<details><summary>{t('展开详情','Read more')}<span aria-hidden="true">＋</span></summary><div class="detail-content">{bullets(details)}</div></details></article>'''

def build():
    base = '' if LANG == 0 else '../'
    locale = t('zh-CN','en')
    name = t('李悦萌','Yuemeng Li')
    nav = [('about',t('关于我','About')),('experience',t('经历','Experience')),('projects',t('项目','Projects')),('skills',t('技能','Skills')),('honors',t('荣誉','Honors')),('contact',t('联系','Contact'))]
    title = t('李悦萌 | 工程 · 研究 · 项目实践','Yuemeng Li | Engineering, Research & Projects')
    description = t('李悦萌的个人主页。北京化工大学控制科学与工程硕士生，关注 MEMS、自动化控制、数据分析与项目协作。','Personal portfolio of Yuemeng Li, a master’s student in Control Science and Engineering at BUCT, working across MEMS, automation, data analysis and project coordination.')
    educations = [
        entry(t('北京化工大学','Beijing University of Chemical Technology'), t('控制科学与工程 · 硕士 · 推免录取','Master’s in Control Science and Engineering · Recommended admission'), t('2024.09 — 2027.07（预计）','Sep 2024 — Jul 2027 (expected)'),t('从控制理论出发，探索微机电系统与单细胞组学的交叉研究。','Exploring the intersection of microelectromechanical systems and single-cell omics, grounded in control theory.'),[t('GPA：3.53 / 4.00，专业排名前 5%。','GPA: 3.53 / 4.00; top 5% of the cohort.'),t('主修课程：现代传感技术、微机电系统、系统辨识与建模。','Key courses: Modern Sensing Technology, Microelectromechanical Systems, System Identification and Modeling.')],['MEMS',t('前 5%','Top 5%')]),
        entry(t('北京化工大学','Beijing University of Chemical Technology'),t('自动化 · 本科','Bachelor’s in Automation'),'2020.09 — 2024.06',t('建立自动控制、电子技术与工程实践的系统基础。','Built a foundation in automatic control, electronics and hands-on engineering.'),[t('GPA：3.52 / 4.33，专业排名前 5%。','GPA: 3.52 / 4.33; top 5% of the cohort.'),t('主修课程：自动控制原理、现代控制理论、过程控制原理、模拟电子技术、数字电子技术。','Key courses: Automatic Control Principles, Modern Control Theory, Process Control, Analog Electronics and Digital Electronics.')])]
    internships = [
        entry(t('瑞声科技','AAC Technologies'),t('项目管理实习生','Project Management Intern'),'2026.06 — 2026.07',t('参与麦克风模组 NPI 项目，支持工程验证到量产导入。','Supported a microphone-module NPI project from engineering validation toward mass production.'),[t('协助维护项目排期与关键节点，跟踪设计、物料、制程、设备及产线准备状态。','Helped maintain schedules and milestones, tracking design, materials, processes, equipment and production-line readiness.'),t('整理试产良率、可靠性、测试一致性及质量验证数据，跟踪关键风险与偏差问题闭环。','Consolidated pilot yield, reliability, test consistency and quality-validation data, and tracked risks and deviations through closure.'),t('项目样品规模由约 11.8K 提升至 20K，产品配置逐步收敛；协助支持阶段推进。','Supported project progression as the sample scale grew from approximately 11.8K to 20K and product configurations converged.')],['NPI',t('项目协作','Project coordination'),t('风险跟踪','Risk tracking')]),
        entry(t('富士康科技集团','Foxconn Technology Group'),t('阳极线控制实习生','Anodizing Line Control Intern'),'2022.07 — 2023.08',t('以数据驱动自动加药逻辑，参与生产线自动化控制调试。','Used process data to develop automatic dosing logic and supported production-line control commissioning.'),[t('监测各工序药池化学浓度，基于采集数据构建自动加药逻辑，使浓度波动降低约 16%，减少人工加药频次。','Monitored chemical concentrations and developed automatic dosing logic using collected data, reducing concentration fluctuations by approximately 16% and the frequency of manual dosing.'),t('参与天车自动化控制调试，测试站点停留时间与运行路径，支持产品在药池间精准搬运。','Helped commission automated overhead-crane controls, testing dwell times and travel paths for precise transfers between process baths.')],[t('自动化控制','Automation'),'−16%']),
        entry(t('深圳远森光电科技有限公司','Shenzhen Yuansen Optoelectronics Technology Co., Ltd.'),t('产品实习生','Product Intern'),'2021.07 — 2021.08',t('调研欧洲 LED / 光电市场，将竞品分析转化为产品优化建议。','Researched the European LED and optoelectronics market, turning competitive analysis into product recommendations.'),[t('收集 30+ 竞品参数与定价数据，开展对标测试与价格弹性分析。','Collected specifications and pricing for 30+ competing products, conducting benchmark tests and price-elasticity analysis.'),t('围绕竞品短板与市场空白提出优化建议，协助新品定价策略与欧洲区推广方案。','Proposed improvements based on competitor limitations and market gaps, and supported pricing and European-market promotion plans.')],[t('竞品分析','Competitive analysis'),t('产品优化','Product improvement')])]
    projects = [
        ('01','MEMS / BIOINFORMATICS',t('基于 MEMS 芯片的<br>单细胞全 RNA 组学研究','MEMS-based single-cell<br>total RNA profiling'),t('2024.09 — 至今 · 项目负责人','Sep 2024 — Present · Project Lead'),t('连接芯片设计、实验验证与测序数据分析，探索单细胞全 RNA 信息的高效采集与检测。','Connecting chip design, experimental validation and sequencing-data analysis to efficiently capture and profile total RNA from individual cells.'),t('从芯片到数据','FROM CHIP TO DATA'),t('已申请国家发明专利','Chinese invention patent application filed'),['MEMS','L-Edit','PDMS','Python','Linux'],[t('负责芯片结构设计、模具光刻、PDMS 倒模及性能测试，根据实验结果持续迭代芯片与实验方案。','Led chip structure design, mold lithography, PDMS casting and performance testing, iterating the chip and experimental protocols based on results.'),t('编写和运行部分数据处理程序，使用 Cutadapt、STAR、featureCounts 完成测序预处理、比对、表达定量及下游分析。','Developed and ran part of the data-processing workflow with Cutadapt, STAR and featureCounts for sequencing preprocessing, alignment, expression quantification and downstream analysis.'),t('国家发明专利申请号：2025115308827。','Chinese invention patent application no. 2025115308827.')]),
        ('02','COMPUTER VISION / AUTOMATION',t('基于人机协同的<br>智能篮球直播系统','Human–machine collaborative<br>basketball broadcasting'),t('2022.11 — 2023.12 · 项目负责人','Nov 2022 — Dec 2023 · Project Lead'),t('从球员与篮球检测，到焦点计算与云台跟踪，让智能摄像装置更好地服务体育赛事直播。','Bringing player and ball detection, focal-point estimation and gimbal tracking together for intelligent sports broadcasting.'),'96%+',t('识别准确率 · 平均检测延迟 < 50 ms','Detection accuracy · Average detection latency < 50 ms'),['Python','YOLOv7',t('目标检测','Object detection'),t('云台控制','Gimbal control')],[t('自建篮球赛事标注数据集，使用 YOLOv7 训练球员和篮球目标检测模型，并在移动端部署。','Built a labeled basketball dataset, trained a YOLOv7 player-and-ball detection model and deployed it on a mobile device.'),t('提出基于最小外接圆拟合的焦点计算方法，通过重心与置信度生成焦点；将坐标无线传输至微控制器，驱动云台自动追踪。','Proposed a focal-point calculation method based on minimum enclosing circle fitting, using centroids and confidence scores; transmitted coordinates wirelessly to a microcontroller for automatic gimbal tracking.'),t('获国家级大学生创新创业训练计划项目荣誉、中国国际大学生创新大赛北京赛区三等奖。','Recognized under the national undergraduate innovation and entrepreneurship training program; awarded third prize in the Beijing division of the China International College Students’ Innovation Competition.')])]
    project_html = ''
    for num,category,pname,date,desc,metric,caption,tags,detail in projects:
        project_html += f'<article class="card project"><div class="project-top"><span class="eyebrow">{category}</span><span class="project-number">{num}</span></div><h3>{pname}</h3><p class="date">{date}</p><p>{desc}</p><div class="project-result"><strong>{metric}</strong><span>{caption}</span></div>{pills(tags)}<details><summary>{t("项目详情","Project details")}<span aria-hidden="true">＋</span></summary><div class="detail-content">{bullets(detail)}</div></details></article>'
    skills = [
        (t('自动化与控制','Automation & control'),['PLC','PID','MATLAB'],t('自动控制原理、控制系统设计、倒立摆建模，以及 PID 参数整定与调试。','Automatic control principles, control-system design, inverted-pendulum modeling, PID tuning and commissioning.')),
        (t('芯片设计与制备','Chip design & fabrication'),['MEMS','L-Edit','AutoCAD','PDMS'],t('微芯片版图设计、软光刻、封装键合与芯片性能测试。','Microchip layout design, soft lithography, packaging and bonding, and chip performance testing.')),
        (t('编程与数据分析','Programming & data'),['Python','C','Linux','STAR','featureCounts'],t('数据处理程序编写，测序数据预处理、序列比对与基因表达定量。','Data-processing scripts, sequencing preprocessing, sequence alignment and gene-expression quantification.')),
        (t('沟通与协作','Communication & coordination'),['CET-4','CET-6','Office','WPS'],t('英语听说读写、项目排期与风险跟踪、跨团队沟通；持全国计算机二级证书。','English communication, project scheduling, risk tracking and cross-team coordination; National Computer Rank Examination Level 2 certificate.'))]
    skill_html = ''.join(f'<article class="card skill"><span class="skill-index">0{i+1}</span><h3>{s[0]}</h3>{pills(s[1])}<p>{s[2]}</p></article>' for i,s in enumerate(skills))
    awards = [
        ('2024 — 2025',t('研究生特等、一等学业奖学金','Special-grade & First-grade Graduate Academic Scholarships'),t('北京化工大学','Beijing University of Chemical Technology')),
        ('2025',t('北京化工大学 — 万集科技奖学金','BUCT–Wanji Technology Scholarship'),t('北京化工大学','Beijing University of Chemical Technology')),
        ('2024',t('中国国际大学生创新大赛 · 北京赛区三等奖','China International College Students’ Innovation Competition · Beijing Third Prize'),t('智能篮球直播系统项目','Intelligent basketball broadcasting project'))]
    award_html = ''.join(f'<div class="award-row"><span class="award-star" aria-hidden="true">✳</span><div><h3>{a[1]}</h3><p>{a[2]}</p></div><span class="date">{a[0]}</span></div>' for a in awards)
    html = f'''<!doctype html>
<html lang="{locale}">
<head>
<meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{title}</title><meta name="description" content="{description}">
<meta name="theme-color" content="#f8f8f5"><meta name="color-scheme" content="light dark">
<link rel="canonical" href="https://marzovo.top/{t('','en/')}">
<link rel="alternate" hreflang="zh-CN" href="https://marzovo.top/"><link rel="alternate" hreflang="en" href="https://marzovo.top/en/"><link rel="alternate" hreflang="x-default" href="https://marzovo.top/">
<meta property="og:type" content="website"><meta property="og:title" content="{title}"><meta property="og:description" content="{description}"><meta property="og:url" content="https://marzovo.top/{t('','en/')}"><meta property="og:locale" content="{t('zh_CN','en_US')}">
<link rel="icon" type="image/svg+xml" href="{base}assets/favicon.svg">
<script src="{base}assets/theme.js"></script><link rel="stylesheet" href="{base}assets/style.css">
<script src="{base}assets/site.js" defer></script>
</head>
<body>
<a class="skip-link" href="#main">{t('跳转到正文','Skip to content')}</a>
<header class="site-header wrap"><a href="{base}index.html" class="brand" aria-label="{t('李悦萌，首页','Yuemeng Li, home')}"><span class="brand-mark" aria-hidden="true">m.</span><span>MarzOvO<span class="brand-dot" aria-hidden="true">✦</span></span></a><nav aria-label="{t('主导航','Main navigation')}">{''.join(f'<a href="#{id}">{label}</a>' for id,label in nav)}</nav><div class="header-controls"><button type="button" class="theme-toggle" aria-label="{t('切换深浅色主题','Toggle color theme')}" aria-pressed="false" hidden><span class="sun" aria-hidden="true">☼</span><span class="moon" aria-hidden="true">☾</span></button><a class="language-toggle" href="{t('en/index.html','../index.html')}" lang="{t('en','zh-CN')}" hreflang="{t('en','zh-CN')}">{t('EN','中文')}<span aria-hidden="true"> ↗</span></a></div></header>
<main id="main" class="wrap">
<section class="hero card" aria-labelledby="intro-title"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span>{t('工程 · 研究 · 项目实践','ENGINEERING · RESEARCH · PROJECTS')}</p><h1 id="intro-title">{t('你好，我是','Hi, I’m')}<br><span class="name-label">{name}</span><span class="hello-star" aria-hidden="true">✳</span></h1><p class="hero-title">{t('把工程思考，<br>变成实际成果。','Turning engineering ideas<br>into real-world outcomes.')}</p><p class="hero-description">{t('北京化工大学控制科学与工程硕士生。<br>在 MEMS、自动化与数据分析的交叉点，<br class="desktop-break">从理解问题出发，用实践推动项目。','A master’s student in Control Science and Engineering at BUCT. Working across MEMS, automation and data analysis, with a hands-on approach to solving problems.')}</p>{pills([t('北京 · 中国','Beijing · China'),t('2027 届硕士','Master’s · Class of 2027')])}<div class="actions"><a class="button primary" href="#projects">{t('看看我的项目','Explore projects')} <span aria-hidden="true">↗</span></a><a class="button" href="{base}assets/resume-zh.pdf" download="Li-Yuemeng-CV-ZH.pdf">{t('下载简历','Download CV (中文)')} <span aria-hidden="true">↓</span></a></div></div>
<aside class="profile-card" aria-label="{t('个人名片','Profile card')}"><div class="id-header"><span>PERSONAL PROFILE</span><span class="id-chip">BUCT</span></div><div class="id-body"><div class="portrait-frame"><img src="{base}assets/portrait.jpg" alt="{t('李悦萌的照片','Portrait of Yuemeng Li')}" width="179" height="251"><div class="photo-caption">Y. M. LI <span>✦</span></div></div><dl><div><dt>NAME</dt><dd>{name}</dd></div><div><dt>{t('专业 / MAJOR','MAJOR')}</dt><dd>{t('控制科学与工程','Control Science<br>& Engineering')}</dd></div><div><dt>{t('当前 / CURRENT','CURRENT')}</dt><dd>{t('硕士研究生','Master’s student')}</dd></div></dl></div><div class="id-footer"><div><span class="tiny-label">CURIOUS MIND, HANDS-ON SPIRIT</span><span class="id-domain">marzovo.top</span></div><span class="seal" aria-hidden="true">M</span></div><div class="id-stripes" aria-hidden="true"></div></aside></section>
<section id="about">{heading('01','关于我','About me','A LITTLE CONTEXT')}<div class="about-grid"><article class="card about-copy"><h3>{t('在技术与实践之间，<br>把每一步做扎实。','Grounded in engineering.<br>Driven by hands-on work.')}</h3><p>{t('我目前在北京化工大学攻读控制科学与工程硕士，本科毕业于同校自动化专业。我的研究聚焦于基于 MEMS 芯片的单细胞全 RNA 组学，工作覆盖芯片设计与制备、实验验证和数据处理。','I’m pursuing a master’s in Control Science and Engineering at Beijing University of Chemical Technology, where I also earned my bachelor’s degree in Automation. My research focuses on MEMS-based single-cell total RNA profiling, spanning chip design and fabrication, experimental validation and data processing.')}</p><p>{t('在瑞声科技、富士康与远森光电的实习中，我接触了新品导入、产线自动化与竞品分析，也逐步积累了项目协作、风险跟踪和问题闭环的实践经验。','Through internships at AAC Technologies, Foxconn and Yuansen Optoelectronics, I gained exposure to new product introduction, production-line automation and competitive analysis, alongside practical experience in coordination, risk tracking and issue resolution.')}</p></article><aside class="card snapshot"><h3>{t('我的经历，一眼看见','At a glance')}</h3><div class="snapshot-row"><strong>03</strong><div><b>{t('段实习经历','Industry internships')}</b><span>{t('产品 · 自动化 · 项目管理','Product · Automation · Project management')}</span></div></div><div class="snapshot-row"><strong>02</strong><div><b>{t('个负责项目','Projects led')}</b><span>{t('MEMS 芯片 · 智能视觉','MEMS chips · Computer vision')}</span></div></div><div class="snapshot-row"><strong>01</strong><div><b>{t('项发明专利申请','Invention patent application')}</b><span>{t('围绕 MEMS 芯片研究','From MEMS chip research')}</span></div></div></aside></div></section>
<section id="experience">{heading('02','学习与工作经历','Experience','LEARN. BUILD. ITERATE.')}<h3 class="subheading">{t('教育背景','Education')}<span>01—02</span></h3><div class="entries">{''.join(educations)}</div><h3 class="subheading">{t('实习经历','Internships')}<span>01—03</span></h3><div class="entries">{''.join(internships)}</div></section>
<section id="projects">{heading('03','精选项目','Selected projects','IDEAS INTO PRACTICE')}<div class="project-grid">{project_html}</div></section>
<section id="skills">{heading('04','技能与工具','Skills & tools','MY TOOLKIT')}<div class="skills-grid">{skill_html}</div></section>
<section id="honors">{heading('05','荣誉与校园实践','Honors & campus life','BEYOND THE LAB')}<div class="card awards">{award_html}</div><article class="card campus"><div class="entry-heading"><div><span class="eyebrow">{t('校园实践','CAMPUS LEADERSHIP')}</span><h3>{t('研究生会学术科技部负责人','Head of Academic & Technology Department')}</h3></div><span class="date">2025.09 — 2026.08</span></div><p>{t('负责部门管理、活动策划与资源协调，组织多场校级、院级学术交流与科技创新活动，在实践中积累大型活动组织、多方协调及团队管理经验。','Managed the graduate student association’s Academic and Technology Department, coordinating resources and organizing university- and school-level academic exchanges and technology events. Gained experience in event delivery, stakeholder coordination and team management.')}</p></article></section>
<section id="contact" class="card contact"><div><p class="eyebrow">LET’S CONNECT</p><h2>{t('期待与你交流。','Let’s start a conversation.')}</h2><p>{t('关于研究、工程实践，或下一次合作。','About research, engineering, or our next opportunity to collaborate.')}</p><div class="actions"><a class="button primary" href="mailto:13683217958@163.com">{t('给我发邮件','Say hello')} <span aria-hidden="true">↗</span></a><button type="button" class="button copy-email" hidden>{t('复制邮箱','Copy email')}</button></div><p id="copy-status" class="copy-status" role="status" aria-live="polite"></p></div><div class="contact-info"><div><span class="tiny-label">EMAIL</span><a href="mailto:13683217958@163.com">13683217958@163.com <span aria-hidden="true">↗</span></a></div><div><span class="tiny-label">GITHUB</span><a href="https://github.com/MarzOvO" target="_blank" rel="noopener noreferrer">@MarzOvO <span aria-hidden="true">↗</span></a></div><a class="text-link" href="{base}assets/resume-zh.pdf" download="Li-Yuemeng-CV-ZH.pdf">{t('下载完整中文简历','Download full CV in Chinese')} ↓</a></div></section>
</main><footer class="wrap"><p>© 2026 {name} <span> / MarzOvO</span></p><a href="#main">{t('保持好奇，认真实践。','Stay curious. Make things happen.')} ↑</a></footer>
</body></html>'''
    destination = ROOT / ('index.html' if LANG == 0 else 'en/index.html')
    destination.parent.mkdir(exist_ok=True)
    destination.write_text(html, encoding='utf-8')
    print(f'Built {destination.relative_to(ROOT)}')

if __name__ == '__main__':
    for LANG in (0,1):
        build()
